name: AutoFishing
version: '${project.version}'
main: wm.vdr.autofishing.AutoFishing
api-version: '1.21'
authors: [ WMGameLive ]
description: Allows players to automatically fish.
folia-supported: true
commands:
  autofishing:
    description: main command.
    usage: /<command>
permissions:
  autofishing.use:
    description: Allow automatic fishing.
    default: op
  autofishing.admin:
    description: Allow to use admin commands.
    default: op
